141 sprachen bei profil hinzufügen
wrth1337/MyCargonaut pull request #185
Opened 2024-02-20 15:41 UTC by Schniggelz

2024-02-20 17:21 UTC, JonathanRech requested changes

2024-02-20 17:21 UTC, JonathanRech commented on frontend/mycargonaut/src/app/main/edit-profile/edit-profile.component.ts
> +    console.log(form.value);
console.log

2024-02-20 17:21 UTC, JonathanRech commented on frontend/mycargonaut/src/app/main/edit-profile/edit-profile.component.ts
> +
languageMap notwendig?

2024-02-20 17:21 UTC, JonathanRech commented on frontend/mycargonaut/src/app/main/edit-profile/edit-profile.component.ts
> +
!! ?

2024-02-20 17:21 UTC, JonathanRech commented on frontend/mycargonaut/src/app/main/profile/profile.component.ts
> +
Map überflüssig.

2024-02-21 10:22 UTC, JonathanRech approved these changes

2024-02-21 15:49 UTC, JonathanRech submitted a review, later dismissed

2024-02-26 13:31 UTC, JonathanRech submitted a review, later dismissed

2024-02-26 13:37 UTC, wrth1337 submitted a review, later dismissed
LGTM!

2024-02-26 13:42 UTC, JonathanRech submitted a review, later dismissed

2024-02-26 14:08 UTC, wrth1337 approved these changes
LGTM!

2024-02-26 14:08 UTC, merged