Unittest für die getUserCoins backend route erstellt
wrth1337/MyCargonaut pull request #186
Opened 2024-02-20 15:49 UTC by marcel951

add getUserCoins unit test
fixes #183

2024-02-22 21:56 UTC, Schniggelz submitted a review, later dismissed

2024-02-23 10:07 UTC, wrth1337 requested changes
1. Meinst du, du könntest die Coins billig per SQL einfach nochmal hochsetzen und dann nochmal getUserCoins aufrufen?
2. Und ich hab gesehen, dass die Route zum erhalten der Coins den kompletten SQL Result zurück gibt. Hier wäre es sauberer, nur die Coins zurückzugeben. Dann muss man z.B. in der Navbar auch nicht auf result.coins.coins zugreifen.

2024-02-27 09:45 UTC, marcel951 commented
guter Hinweis, das Coins return habe ich angepasst

Das hoch und heruntersetzen würde ich dann mit dem Issue #190 betrachten

2024-02-27 10:03 UTC, wrth1337 approved these changes
LGTM!

2024-02-27 11:46 UTC, JonathanRech approved these changes
LGTM

2024-02-27 11:46 UTC, merged