184 user story als benutzerin möchte ich kommentare zu einem ad hinzufügen können um fragen oder sonstiges zu klären
wrth1337/MyCargonaut pull request #193
Opened 2024-02-27 10:51 UTC by wrth1337

2024-02-27 13:31 UTC, JonathanRech requested changes

2024-03-01 07:47 UTC, wrth1337 commented on frontend/mycargonaut/src/app/chat/chat.component.html
> +      <svg (click)="sendMessage()" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="currentColor" class="bi bi-send-fill" viewBox="0 0 16 16" style="align-self: center">
Ist mit commit [f2873ca](https://github.com/wrth1337/MyCargonaut/pull/193/commits/f2873ca584708e4ba0cb68dc389458067536b41c) gefixt.

2024-03-01 08:37 UTC, marcel951 approved these changes
LGTM!

2024-03-01 09:22 UTC, JonathanRech approved these changes
LGTM

2024-03-01 09:53 UTC, merged