196 profil komponente auslagern
wrth1337/MyCargonaut pull request #200
Opened 2024-03-05 13:25 UTC by Schniggelz

2024-03-06 14:51 UTC, JonathanRech requested changes

2024-03-06 14:51 UTC, JonathanRech commented on frontend/mycargonaut/src/app/main/create-offer/create-offer.component.css
> +
Sollte vermutlich nicht in diesem Issue gemacht werden.

2024-03-06 15:03 UTC, JonathanRech approved these changes
LGTM

2024-03-07 13:54 UTC, marcel951 approved these changes

2024-03-08 08:06 UTC, marcel951 approved these changes

2024-03-08 10:29 UTC, wrth1337 approved these changes
Lgtm!

2024-03-08 11:07 UTC, merged