Update DB Schema
wrth1337/MyCargonaut pull request #210
Opened 2024-03-08 04:59 UTC by hannafeddersen

Anpassen des DB Schemas an die aktuelle DB Tabellen. 

![ERD-Cargonaut](https://github.com/wrth1337/MyCargonaut/assets/115730773/d2ae7316-ab62-4ddb-822f-5a90629df668)

2024-03-08 10:18 UTC, JonathanRech requested changes
Die Datenbank hat sich deutlich verändert im vergleich zu diesem Schema, also auch das neue Schema ist veraltet. Außerdem ist glaube ich ein Transparenter Hintergrund gar nicht so gut, da man das dann auf  dunklem Hintergrund nicht lesen kann.

2024-03-08 18:50 UTC, hannafeddersen commented
Dann sind die DB Änderungen noch nicht im Dev Branch gemergt :) Das Schema habe ich dem init.sql angepasst. Würde das Issue erstmal zurückstellen und es ganz zum Schluss machen. Den Hintergrund kann ich natürlich ändern. @JonathanRech

2024-03-08 23:38 UTC, JonathanRech commented
Ja es gibt auch noch Änderungen die nicht auf dem Dev sind, die meisten sind es aber. Zb gibt es keine Status Tabelle mehr. Aber das ganze kurz zurückzustellen ist vermutlich besser ja.

2024-03-16 13:43 UTC, wrth1337 commented
Wird mit dem Doku-Update Branch hinzugefügt.

Fixed with  #226.

2024-03-16 13:44 UTC, closed without merging