204 als anwender möchte ich meinem account geld hinzufügen können
wrth1337/MyCargonaut pull request #215
Opened 2024-03-08 15:02 UTC by marcel951

closes #204

### :ballot_box_with_check: Definition of Done checklist
- [x] Frontend
  - [x] Are all functions implemented?
  - [x] Are there front-end tests that test the appearance of the mockup?
  - [ ] Do the associated components look like the mockup?
- [x] Backend
  - [x] Are all necessary routes documented via swagger?
  - [x] Are all necessary methods tested via Jest (positive and negative tests)?
- [x] Is the user story finished to such an extent that no further work is required after the pull request (excluding hotfixes and adjustments)?

2024-03-09 17:58 UTC, marcel951 commented
@wrth1337  Ich erhalte im backend test einen Fehler bei der Altersprüfung.  Ist der Fehler bereits bekannt?

2024-03-09 18:24 UTC, wrth1337 commented
musste @Schniggelz fragen, der hat das gecoded

2024-03-10 18:47 UTC, Schniggelz commented on frontend/mycargonaut/src/app/main/coin-modal/coin-modal.component.ts
> +      console.log(res);
console.logs noch entfernen

2024-03-11 11:01 UTC, wrth1337 requested changes
Ein Typo noch drinne

2024-03-11 11:01 UTC, wrth1337 commented on frontend/mycargonaut/src/app/main/coin-modal/coin-modal.component.html
> +            <p>Diese Funktion befindet sich im Aufbau, in der späteren Anwendung wird hier ein Lastschrift einzug oder Paypal hinterlegt.</p>
Lastschrifteinzug ist ein Wort.

2024-03-12 13:45 UTC, wrth1337 approved these changes
LGTM!

2024-03-12 13:51 UTC, merged