208 profil und profildaten umbauen und so
wrth1337/MyCargonaut pull request #216
Opened 2024-03-11 13:23 UTC by Schniggelz

2024-03-12 16:09 UTC, JonathanRech approved these changes
lgtm

2024-03-13 15:22 UTC, wrth1337 requested changes
Kleine Änderung

2024-03-13 15:22 UTC, wrth1337 commented on backend/test/profile.test.js
> +    const firstName = 'testFirstName';
Bitte hier einmal alle Mockdaten abändern, führt sonst wieder zu Test-Fehlern.
z.B. profileTestFirstName, profileTestEmail@test.com

usw

2024-03-13 15:24 UTC, marcel951 requested changes

2024-03-13 15:24 UTC, marcel951 commented on backend/test/profile.test.js
> +    const email = 'testEmail@test.com';
Bitte die Mail noch etwas abändern. z.B. "testProfile@mail.de" 
Hintergrund: Eventuell schlagen dann die Backend Tests fehl, wenn der User bereits existiert

2024-03-13 15:24 UTC, marcel951 commented on backend/test/user.test.js
> -    expect(await isOver18yo('2006-03-08')).toBeTruthy();
Eventuell hier mit Sysdate - x arbeiten um den Edgecase zu testen?

2024-03-13 15:43 UTC, wrth1337 approved these changes
LGTM!

2024-03-13 15:53 UTC, marcel951 approved these changes
LGTM!

2024-03-13 15:56 UTC, merged